### ISSUE TITLE
Audio missing when headphones are unplugged 

### ISSUE THREAD

**Issue by nicolettemanas** [twilio/voice-quickstart-objc#25]
Hi team,

I am having problems regarding audio using 2.0.0-beta7. Please see ff steps to reproduce the issue:

1. Ongoing call between user1(caller) and user2(receiver)
2. User2 plug headphones
3. User2 unplug headphones

**Result:** Audio is missing. Audio still missing on succeeding calls unless app is restarted or re-installed.

**User1:** iPhone6s iOS10.1.1
**User2:** iPad2 iOS9.3.2

This is using the sample app you provided.
I'm not sure if it is device-related or iOS version-related, though we have tested it using iOS8 and it seems to be working fine.

**Comment by bobiechen-twilio** [comment]
Hi @nicolettemanas 
Thanks for reporting the issue. I've logged a ticket and we will take a look at the issue.
In the meantime it would be great if you could also provide us the SDK log when this issue happens.

-bobie

**Comment by bobiechen-twilio** [comment]
Hi @nicolettemanas 

I am sorry for my delay of getting back to you. I've tested the scenario with both our internal testapp and the quickstart sample (callkit or non-callkit) but unfortunately couldn't reproduce the audio problem you saw. Could you try the newly released beta8 with the device again and provide us the SDK log if you run into the same issue? Thanks!

Again I apologize for the lack of interaction on this issue.

-bobie

**Comment by milkmanjr** [comment]
@bchen-twilio  running across the same issue an app.

Reproducing with bluetooth headset. Steps to reproduce:

1. connect with headset on, then disconnect. At this point everything is fine.
2. go to another application (in my case Spotify) and play audio for 10 seconds. pause it.
3. go back to the phone application and try and make a call. no audio.

At this point there is no audio. I will try with the latest beta8 and reporting my findings.

**Comment by milkmanjr** [comment]
The issue seems to be resolved in beta8.

**Comment by bobiechen-twilio** [comment]
Thanks for trying @milkmanjr for glad to know it's resolved in beta8!

**Comment by nicolettemanas** [comment]
Hi @bchen-twilio 

Problem still persists in beta8. Please see ff. DEBUG level logs:

```
2017-04-17 10:36:10.642 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:10.664 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 2 empty/lost)
2017-04-17 10:36:10.764 -[770:226068] [DEBUG TVORTCMonitor] Inside checkCrossingThreshold:checkLow:isFloat, 1 samples exceed the packets_lost_fraction threshold
2017-04-17 10:36:11.755 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:11.756 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:11.765 -[770:226036] [DEBUG TVORTCMonitor] Inside checkCrossingThreshold:checkLow:isFloat, 1 samples exceed the packets_lost_fraction threshold
2017-04-17 10:36:12.475 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:12.500 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:12.764 -[770:226068] [DEBUG TVORTCMonitor] Inside checkCrossingThreshold:checkLow:isFloat, 1 samples exceed the packets_lost_fraction threshold
2017-04-17 10:36:13.500 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:13.523 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:13.765 -[770:226068] [DEBUG TVORTCMonitor] Inside checkCrossingThreshold:checkLow:isFloat, 1 samples exceed the packets_lost_fraction threshold
2017-04-17 10:36:14.034 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:14.056 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:14.545 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:14.545 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:14.764 -[770:226068] [DEBUG TVORTCMonitor] Inside checkCrossingThreshold:checkLow:isFloat, 1 samples exceed the packets_lost_fraction threshold
2017-04-17 10:36:14.776 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:14.777 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:14.985 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:14.986 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:15.240 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:15.265 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:15.449 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:15.450 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:15.636 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:15.658 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:15.765 -[770:226036] [DEBUG TVOEventPublisher] Publishing event to Twilio Endpoint Analytics
2017-04-17 10:36:15.821 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:15.845 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:16.029 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:16.030 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:16.214 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:16.239 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:16.449 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:16.470 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:16.658 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:16.658 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:16.820 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:16.842 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:17.029 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:17.029 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:17.214 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:17.238 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:17.400 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:17.400 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:17.509 -[770:226069] [DEBUG TVOEventPublisher] TwilioVoiceClient Endpoint-Analytic HTTP response - status: 200, error: (null)
2017-04-17 10:36:17.587 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:17.608 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:17.796 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:17.796 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:17.959 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:17.980 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:18.167 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:18.168 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:18.353 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:18.375 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:18.539 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:18.539 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:18.725 -[770:226103] PJSIP(5): strm0x154a8014  Frame lost, recovered!
2017-04-17 10:36:18.746 -[770:226103] PJSIP(5): strm0x154a8014  Jitter buffer starts returning normal frames (after 1 empty/lost)
2017-04-17 10:36:20.031 -[770:226069] PJSIP(4):    pjsua_aud.c !.Closing iPhone IO device sound playback device and iPhone IO device sound capture device
2017-04-17 10:36:20.036 -[770:226069] PJSIP(4): coreaudio_dev.  .core audio stream stopped
2017-04-17 10:36:25.765 -[770:226068] [DEBUG TVOEventPublisher] Publishing event to Twilio Endpoint Analytics
2017-04-17 10:36:27.422 -[770:226128] [DEBUG TVOEventPublisher] TwilioVoiceClient Endpoint-Analytic HTTP response - status: 200, error: (null)
2017-04-17 10:36:27.631 -[770:226086] [DEBUG Twilio] on_transport_state(): 3
2017-04-17 10:36:27.637 -[770:226086] PJSIP(4): tlsc0x1556fa14 !TLS transport destroyed normally
2017-04-17 10:36:27.764 -[770:226069] [WARN TVORTCMonitor] Inside raiseWarningForThreshold:, invalid warning event payload
2017-04-17 10:36:28.765 -[770:226069] [WARN TVORTCMonitor] Inside raiseWarningForThreshold:, invalid warning event payload
2017-04-17 10:36:28.765 -[770:226069] [DEBUG TVOCall] Inside rtcMonitor:didClearWarning:, warning: constant-audio-output-level
2017-04-17 10:36:28.768 -[770:226069] [DEBUG TVOEventPublisher] Publishing event to Twilio Endpoint Analytics
2017-04-17 10:36:29.764 -[770:226069] [DEBUG TVOCall] Inside rtcMonitor:didClearWarning:, warning: constant-audio-input-level
2017-04-17 10:36:29.766 -[770:226069] [DEBUG TVOEventPublisher] Publishing event to Twilio Endpoint Analytics
```

These logs are from the time when the user plugs in the headphones up to the time of unplugging it. I tried to compare it with the logs of the working device and it seems that the lines: 

```
2017-04-17 10:36:20.031 -[770:226069] PJSIP(4):    pjsua_aud.c !.Closing iPhone IO device sound playback device and iPhone IO device sound capture device
2017-04-17 10:36:20.036 -[770:226069] PJSIP(4): coreaudio_dev.  .core audio stream stopped
```

are only printed after ending the call. I'm not sure why they are shown when the headphones are unplugged in iPad2. 

I've also attached the logs [here](https://github.com/twilio/voice-quickstart-objc/files/924843/no-audio-debug-logs.txt) of a call succeeding this scenario wherein no audio is present during the whole call. 

I apologize for the late revert. I hope this helps.

Thanks!

**Comment by bobiechen-twilio** [comment]
Hi @nicolettemanas 

I've checked both logs you provided.
For the unplug-and-plug issue, unfortunately I didn't find any immediate error from the log. I am going to try myself with the iPads in the office and see if it's really a device related issue.
For the second log of the no-audio issue, I am seeing internal IP addresses (192.168.x.x) and that could cause the Twilio Voice service trouble, especially the audio media part. Although it's not explicitly mentioned [here](https://support.twilio.com/hc/en-us/articles/223180888-What-are-Twilio-Client-s-network-connectivity-requirements-), but typically we would recommend that you check if there is any firewall set up on the specific network.

I am sorry that this is taking longer than we expected to figure out what is going on.
Please bear with us.

-bobie

**Comment by nicolettemanas** [comment]
Hi @bchen-twilio 

The TwilioVideo team are able to reproduce this issue on the same device (iPad2) according to this [github issue.](https://github.com/twilio/video-quickstart-objc/issues/61#issuecomment-296261448) Perhaps you could check with them?

I am yet to check the no-audio issue with another network. I'll get back to you once I have tested it.

Thanks!

**Comment by bobiechen-twilio** [comment]
Hi @nicolettemanas 

Sorry I was out of the States for a couple of days.
Thanks for letting me know. I'll check with the team and make sure I use the same device for testing the issues again.
Please stay tuned.

-bobie

**Comment by bobiechen-twilio** [comment]
Closing this issue for now since this is only happening on specific device model.
