### ISSUE TITLE
Once Call is Connected, No Audio is passed between devices

### ISSUE THREAD

**Issue by nkarman** [twilio/voice-quickstart-objc#50]
### Description

We have a bit of a unique case, as we are using react-native for our application. Essentially, we have a javascript wrapper around the Objective C Voice Quickstart code to handle our calling. We are using this node module for this: https://github.com/hoxfon/react-native-twilio-programmable-voice

Has Occurred when attempting to connect iPhone to iPhone using VoiceClient

On connect():

1. Call rings
2. Recipient receives call notification
3. On pickup, call appears to be connected, but no audio is passed

### Steps to Reproduce

1. Dial a user who is logged in and and is registered for VoIP push notifications

#### Expected Behavior

Upon Pickup, Call works as expected

#### Actual Behavior

Call stops ringing and call appears to be connected, but no audio is passed.

#### Logs

Logs in pastebin below
https://pastebin.com/ANhrM98i

#### Voice iOS SDK

[e.g. 2.0.0-beta8 via CocoaPods]

#### Xcode

[e.g. 8.3.3]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

 iPhone 6 -> iPhone 7+

**Comment by bobiechen-twilio** [comment]
Hi @nkarman 

Bobie from the Voice SDK team and I'd like to thank you for choosing the Twilio Programmable Voice iOS SDK, and especially for following the issue template and providing SDK log 👍 
We've fixed a few bugs around call audio issues in recent beta release. It would be great if you could update the SDK reference with the latest beta13 ([changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)) and hopefully that should resolve the no-audio issue you are experiencing. Please note that there are a few API deltas between beta8 and beta13.

Thanks
-bobie

**Comment by fabriziomoscon** [comment]
@nkarman I have just pushed version `2.5.0` on npm for `react-native-twilio-programmable-voice`, which uses `2.0.0-beta13`.
It solves few bugs as @bchen-twilio said.

Please let me know if that works for you.

**Comment by nkarman** [comment]
@fabriziomoscon Thanks so much! Really appreciate all the work you have done on this module!

**Comment by bobiechen-twilio** [comment]
Thanks @fabriziomoscon 👍  🙇 
I am assuming with the latest version from Fabrizio the audio issue is fixed?

**Comment by benminer** [comment]
Hey @bchen-twilio, I am the other front-end developer working with @nkarman on this particular project. We have had some React Native version issues, but they are resolved so I will be trying this new version out later today and will keep you guys updated. Thanks so much for being so responsive on this issue.

**Comment by bobiechen-twilio** [comment]
Thanks a lot @benminer!

**Comment by Pagebakers** [comment]
~~I've just updated to beta 13 and i'm still experiencing these audio issues. I'm not seeying any specific useful info in the logs. Any pointers where I should look?~~

It miraculously solved itself, thanks :)

**Comment by bobiechen-twilio** [comment]
Thanks for trying the latest version and confirming the problem has been fixed @nkarman @benminer @Pagebakers. I'll close this one and please feel free to reach out to us if you run into any issue in the future.
Thanks again for the awesome RN integration @fabriziomoscon 🙇
